// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CreateParticle

int _particleTexWidth;
RWTexture2D<float4> _particleResultTex;
[numthreads(32, 32, 1)]
void CreateParticle(uint3 pixel : SV_DispatchThreadID) {
	float texWidth = (float)_particleTexWidth;
	float x = pixel.x - texWidth / 2.0;
	float y = pixel.y - texWidth / 2.0;
	float light = 1 - ((x * x + y * y) / (texWidth * texWidth / 5.0));
	_particleResultTex[pixel.xy] = float4(1, 1, 1, 1) * light;
}